In [55]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

In [56]:
billboard=pd.read_csv("C:/Users/nyc15/Desktop/파이썬 공부/drive-download-20200703T073348Z-001/0910/padas_data/data/billboard.csv")
billboard.head()

year        artist                    track  time date.entered  wk1   wk2  \
0  2000         2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   87  82.0   
1  2000       2Ge+her  The Hardest Part Of ...  3:15   2000-09-02   91  87.0   
2  2000  3 Doors Down               Kryptonite  3:53   2000-04-08   81  70.0   
3  2000  3 Doors Down                    Loser  4:24   2000-10-21   76  76.0   
4  2000      504 Boyz            Wobble Wobble  3:35   2000-04-15   57  34.0   

    wk3   wk4   wk5  ...  wk67  wk68  wk69  wk70  wk71  wk72  wk73  wk74  \
0  72.0  77.0  87.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
1  92.0   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
2  68.0  67.0  66.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3  72.0  69.0  67.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4  25.0  17.0  17.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

   wk75  wk76  
0   NaN   NaN  
1   NaN   NaN  
2   NaN   NaN  
3   NaN   NaN  
4   NaN   NaN  

[5 rows x 81 columns]

In [57]:
billboard_long=pd.melt(billboard, id_vars=['year','artist','track','time','date.entered'],var_name='week', value_name='rating')
billboard_long.head()

year        artist                    track  time date.entered week  rating
0  2000         2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk1    87.0
1  2000       2Ge+her  The Hardest Part Of ...  3:15   2000-09-02  wk1    91.0
2  2000  3 Doors Down               Kryptonite  3:53   2000-04-08  wk1    81.0
3  2000  3 Doors Down                    Loser  4:24   2000-10-21  wk1    76.0
4  2000      504 Boyz            Wobble Wobble  3:35   2000-04-15  wk1    57.0

In [58]:
billboard_long[billboard_long.track=='Loser']

year        artist  track  time date.entered  week  rating
3      2000  3 Doors Down  Loser  4:24   2000-10-21   wk1    76.0
320    2000  3 Doors Down  Loser  4:24   2000-10-21   wk2    76.0
637    2000  3 Doors Down  Loser  4:24   2000-10-21   wk3    72.0
954    2000  3 Doors Down  Loser  4:24   2000-10-21   wk4    69.0
1271   2000  3 Doors Down  Loser  4:24   2000-10-21   wk5    67.0
...     ...           ...    ...   ...          ...   ...     ...
22510  2000  3 Doors Down  Loser  4:24   2000-10-21  wk72     NaN
22827  2000  3 Doors Down  Loser  4:24   2000-10-21  wk73     NaN
23144  2000  3 Doors Down  Loser  4:24   2000-10-21  wk74     NaN
23461  2000  3 Doors Down  Loser  4:24   2000-10-21  wk75     NaN
23778  2000  3 Doors Down  Loser  4:24   2000-10-21  wk76     NaN

[76 rows x 7 columns]

In [59]:
billboard_songs=billboard_long[['year', 'artist', 'track', 'time']]
billboard_songs

year            artist                    track  time
0      2000             2 Pac  Baby Don't Cry (Keep...  4:22
1      2000           2Ge+her  The Hardest Part Of ...  3:15
2      2000      3 Doors Down               Kryptonite  3:53
3      2000      3 Doors Down                    Loser  4:24
4      2000          504 Boyz            Wobble Wobble  3:35
...     ...               ...                      ...   ...
24087  2000       Yankee Grey     Another Nine Minutes  3:10
24088  2000  Yearwood, Trisha          Real Live Woman  3:55
24089  2000   Ying Yang Twins  Whistle While You Tw...  4:19
24090  2000     Zombie Nation            Kernkraft 400  3:30
24091  2000   matchbox twenty                     Bent  4:12

[24092 rows x 4 columns]

In [60]:
#중복데이터 제거
billboard_songs=billboard_songs.drop_duplicates()
billboard_songs.head()

year        artist                    track  time
0  2000         2 Pac  Baby Don't Cry (Keep...  4:22
1  2000       2Ge+her  The Hardest Part Of ...  3:15
2  2000  3 Doors Down               Kryptonite  3:53
3  2000  3 Doors Down                    Loser  4:24
4  2000      504 Boyz            Wobble Wobble  3:35

In [61]:
## 데이터 입력 시 오타가 날 수 있다는 가정을 염두해 두고
#  id 컬럼 추가
billboard_songs['id']=range(len(billboard_songs))
billboard_songs.head()

year        artist                    track  time  id
0  2000         2 Pac  Baby Don't Cry (Keep...  4:22   0
1  2000       2Ge+her  The Hardest Part Of ...  3:15   1
2  2000  3 Doors Down               Kryptonite  3:53   2
3  2000  3 Doors Down                    Loser  4:24   3
4  2000      504 Boyz            Wobble Wobble  3:35   4

In [62]:
#billboard_long.merge(billboard_songs)
billboard_ratings=billboard_long.merge(billboard_songs, on=['year', 'artist', 'track', 'time'])
billboard_ratings

year           artist                    track  time date.entered  \
0      2000            2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   
1      2000            2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   
2      2000            2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   
3      2000            2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   
4      2000            2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   
...     ...              ...                      ...   ...          ...   
24087  2000  matchbox twenty                     Bent  4:12   2000-04-29   
24088  2000  matchbox twenty                     Bent  4:12   2000-04-29   
24089  2000  matchbox twenty                     Bent  4:12   2000-04-29   
24090  2000  matchbox twenty                     Bent  4:12   2000-04-29   
24091  2000  matchbox twenty                     Bent  4:12   2000-04-29   

       week  rating   id  
0       wk1    87.0    0  
1       wk2    82.0    0  
2       wk3    72.0    0  
3       wk4    77.0    0  
4       wk5    87.0    0  
...     ...     ...  ...  
24087  wk72     NaN  316  
24088  wk73     NaN  316  
24089  wk74     NaN  316  
24090  wk75     NaN  316  
24091  wk76     NaN  316  

[24092 rows x 8 columns]

### 배열 연결 stack, vstack, hstack

In [63]:
#hstack : 행의 수가 같은 두 개 이상의 배열을 연결 -> 열이 증가
# horizontal
a1=np.ones((2,3))
a2=np.zeros((2,2))
#a1과 a2는 행의 수가 동일 2 x 3 2 x 2
np.hstack([a1,a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [64]:
#vstack : 열의 수가 같은 두 개 이상의 배열을 연결 -> 행이 증가
# vertical
a1=np.ones((2,3))
a2=np.zeros((3,3))
#a1과 a2는 열의 수가 동일
np.vstack([a1,a2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [65]:
#dstack : (depth) 방향으로 배열을 연결
#(3*4), (3*4) => dstack => (3*4*2) #2차원 배열 2개 연결하여 3차원 배열 1개 생성
a1=np.ones((3,4))
a2=np.zeros((3,4))
#a1과 a2는 열의 수가 동일
print(np.dstack([a1,a2]))
np.dstack([a1,a2]).shape #(3, 4, 2)   ==   (행, 열, 깊이)

[[[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]]


(3, 4, 2)

In [66]:
### 인덱서로 배열 연결 (대괄호가 붙는 함수를 인덱서라고 부름)

In [67]:
# r : 차원 증가 row + 좌우 붙이기 
np.r_[np.array([1,2,3]),np.array([4,5,6])]
#두 배열을 좌우로 연결(hstack함수와 비슷)

array([1, 2, 3, 4, 5, 6])

In [68]:
# c : 차원증가 columns + 좌우 붙이기 
np.c_[np.array([1,2,3]),np.array([4,5,6])]
#두 배열을 차원을 증가시킨 후 좌우로 연결(차원 증가 -> hstack)


array([[1, 4],
       [2, 5],
       [3, 6]])

### 데이터프레임 인덱스 조작(설정/제거) 
set_index:기존 행 인덱스를 제거하고, 데이터 컬럼 중 어느 하나를 인덱스로 설정   
reset_index:기존 행 인덱스를 제거하고, 제거된 행 인덱스를 데이터 열로 추가  

In [69]:
myList=list("ABCDE") 
myArr=np.round(np.random.rand(3,5),2) # 소수점 이하 2
np.vstack([myList,myArr]) #4,5
df1=pd.DataFrame(np.vstack([myList,myArr]).T,columns=['C1','C2','C3','C4']) 
df1

C1    C2    C3    C4
0  A  0.03  0.02  0.91
1  B  0.28  0.98  0.39
2  C  0.65  0.62   0.6
3  D  0.57   0.9   0.1
4  E  0.01  0.16  0.81

In [70]:
df2=df1.set_index('C1') # 열을 인덱스로 지정
df2

C2    C3    C4
C1                  
A   0.03  0.02  0.91
B   0.28  0.98  0.39
C   0.65  0.62   0.6
D   0.57   0.9   0.1
E   0.01  0.16  0.81

In [71]:
df2.reset_index()

C1    C2    C3    C4
0  A  0.03  0.02  0.91
1  B  0.28  0.98  0.39
2  C  0.65  0.62   0.6
3  D  0.57   0.9   0.1
4  E  0.01  0.16  0.81

### 다중 인덱스 MultiIndex.from_tuple / columns = [[],[]]

In [72]:
mi=pd.MultiIndex.from_tuples([('A','C1'),('A','C2'),
                          ('B','C3'),('B','C4')])
data=pd.DataFrame(np.random.randn(5,4),
            columns=mi)
data

A                   B          
         C1        C2        C3        C4
0  0.128324  0.182475  1.202036  0.233762
1 -0.840480 -0.210597  0.452724 -0.063061
2 -0.504372  0.248918 -1.142993 -0.161620
3 -1.079285 -0.229096 -1.639086  0.778173
4  1.012349 -0.066505 -0.174302  0.086727

In [73]:
df3=pd.DataFrame(np.random.randn(5,4),
                 columns=[["A","A","B","B"],
                          ["C1","C2","C3","C4"]])
df3

A                   B          
         C1        C2        C3        C4
0 -0.865824  0.769329 -0.875141 -0.074405
1 -1.188551 -0.654996  0.822876 -0.492696
2 -1.025838  0.633095 -1.052431  0.813304
3 -2.022808  0.327290 -1.876824  1.175752
4  0.809385  1.542866 -0.893088  0.298686

In [74]:
df4=pd.DataFrame(np.random.randn(6,4),
            columns=[['A','A','B','B'],
                    ['C','D','C','D']],
            index=[['M','M','M','F','F','F'],
                  ["id"+str(i+1) for i in range(3)]*2])
df4.columns.names=['cidx1', 'cidx2']
df4.index.names=['ridx1','ridx2']
df4

cidx1               A                   B          
cidx2               C         D         C         D
ridx1 ridx2                                        
M     id1   -0.409303  1.339076  0.141371  0.823284
      id2    0.017476 -1.076229 -1.228130  0.318431
      id3    0.810652 -0.474500  0.814865  0.111410
F     id1    0.688840  0.316169 -1.164735 -0.033924
      id2   -0.443356  1.154532 -0.031518  0.316356
      id3    0.195304  1.133345 -0.008701  1.927048

# 연관 규칙

In [75]:
"""
연관규칙
규칙?(rules) : if 조건식 then 결과   (if A -> B)
연관규칙 : 특정 사건 발생 -> 함께 발생하는 또 다른 사건 간의 규칙
항목집합(item set):전체 항목 집합으로부터 만들어 질 수 있는 모든 각각의 부분 집합
X={a,b,c}= 2의 3승
   2*2*2
X의 부분집합? 공집합...전체집합
공집합, a, b, c, ab, ac, bc, abc

a->b
ac->b
...

이마트 : item이 1만가지 => 이마트전체상품집합={a1,a2,...a10000}=>2의 10000승
=> 돈 워리 => 연관규칙(apriori) => pruning(prune, 가지치기)

연관규칙?특정 항목 집합이 발생했을 때 또 다른 항목 집합이 발생하는 규칙
연관규칙의 예 : {채소} -> {마요네즈}, {채소, 음료} -> {마요네즈}, ...
{채소}->{시럽, 식초}, ...

*의미있는 연관 규칙을 발견 -> 기준(support(지지도),confidence(신뢰도),lift(향상도))에 부합되는 연관 규칙을 필터링
=> 특히 향상도가 중요함.

{맥주}->{땅콩}

{물티슈}->{강아지사료}

{물티슈}->{컵라면}?물티슈를 사고, 강아지와 함께 산책을 나가고, 공원에서 컵라면

{건전지}->{컵라면}?서귀포점 이마트 -> adaptive recommender system
"""

'\n연관규칙\n규칙?(rules) : if 조건식 then 결과   (if A -> B)\n연관규칙 : 특정 사건 발생 -> 함께 발생하는 또 다른 사건 간의 규칙\n항목집합(item set):전체 항목 집합으로부터 만들어 질 수 있는 모든 각각의 부분 집합\nX={a,b,c}= 2의 3승\n   2*2*2\nX의 부분집합? 공집합...전체집합\n공집합, a, b, c, ab, ac, bc, abc\n\na->b\nac->b\n...\n\n이마트 : item이 1만가지 => 이마트전체상품집합={a1,a2,...a10000}=>2의 10000승\n=> 돈 워리 => 연관규칙(apriori) => pruning(prune, 가지치기)\n\n연관규칙?특정 항목 집합이 발생했을 때 또 다른 항목 집합이 발생하는 규칙\n연관규칙의 예 : {채소} -> {마요네즈}, {채소, 음료} -> {마요네즈}, ...\n{채소}->{시럽, 식초}, ...\n\n*의미있는 연관 규칙을 발견 -> 기준(support(지지도),confidence(신뢰도),lift(향상도))에 부합되는 연관 규칙을 필터링\n=> 특히 향상도가 중요함.\n\n{맥주}->{땅콩}\n\n{물티슈}->{강아지사료}\n\n{물티슈}->{컵라면}?물티슈를 사고, 강아지와 함께 산책을 나가고, 공원에서 컵라면\n\n{건전지}->{컵라면}?서귀포점 이마트 -> adaptive recommender system\n'

In [76]:
"""
X,Y : 공통 원소가 없는 항목 집합
ex)X -> Y : {건전지}->{컵라면} 
X->Y : if X then Y라는 연관 규칙
N : 전체 거래 건수
n(X) : 항목 집합 X의 거래 건수
n(Y) : 항목 집합 Y의 거래 건수

1) 지지도?
두 항목 집합 X와 Y의 지지도? 전체 거래 건수 중에서 항목 집합 X와 Y를 모두 포함하는
거래건수의 비율.
표기 예) s(X->Y) : X를 구매하면 Y를 구매한다 라는 규칙에 대한 지지도
s(X->Y) =  X와 Y를 모두 포함하는 거래 건수 / 전체 거래 건수

2)신뢰도?
항목 집합 X를 포함하는 거래(n(X)) 중에서, 항목 집합 Y를 포함하고 있는 거래의 비율
(조건부 확률).
표기 예) c(X->Y) : X를 구매하면 Y를 구매한다 라는 규칙에 대한 신뢰도
c(X->Y) =  X와 Y를 모두 포함하는 거래 건수 / 항목 집합 X가 포함된 거래 건수

3)향상도?
항목 집합 X가 주어지지 않았을때의 항목집합 Y의 확률 대비 
항목 집합 X가 주어졌을때의 항목집합 Y의 확률 증가 비율.
=> 향상도가 1보다 크거나(+관계) 작다면(-관계) 우연적 기회(random chance)보다
우수함을 의미. (X와 Y가 서로 독립이면 Lift=1)

표기 예) Lift(X->Y) : 연관규칙의 신뢰도 / 지지도 = c(X->Y) / s(Y)
-------------------------------------------------------------------------------------
*예시 데이터( 총 5건, 각 아이템이 2개 이상 중복되는 경우에도 아이템 1개로 간주)*
거래번호   아이템
1         계란, 우유
2         계란, 기저귀, 맥주, 사과
3         우유, 기저귀, 맥주, 콜라
4         계란, 우유, 맥주, 기저귀 
5         계란, 우유, 맥주, 콜라

N=5(전체 거래 건수)
n(기저귀)=3
n({계란,우유})=3

X={계란, 맥주}, Y={기저귀} 인 경우.
1)지지도 계산(s(X->Y))
   2  /  5 = 0.4
   
2)신뢰도 계산(c(X->Y))   
      2  /  3 = 0.667
      
3)향상도 계산(Lift(X->Y)) = c(X->Y) / s(Y)
s(Y): 전체 거래 중에서 Y거래 건수의 비율


Lift(X->Y) ? Lift({계란, 맥주} -> {기저귀})

=                           (  2  /    3  )                 /  (   3      /   5   )
= (계란,맥주,기저귀가 모두 포함된수/계란,맥주가 모두 포함된수)/ (기저귀건수/전체건수)
=   0.333 / 0.6 => 1보다 약간 큼

= 0.01  / 0.2


c(X->Y) =  X와 Y를 모두 포함하는 거래 건수 / 항목 집합 X가 포함된 거래 건수
"""

# 항목 집합 X가 주어지지 않았을때의 항목집합 Y의 확률 (분모) 대비 
# 항목 집합 X가 주어졌을때의 항목집합 Y의 확률 증가 비율.
# => 향상도가 1보다 크거나(+관계) 작다면(-관계) 우연적 기회(random chance)보다
# 우수함을 의미. (X와 Y가 서로 독립이면 Lift=1)








'\nX,Y : 공통 원소가 없는 항목 집합\nex)X -> Y : {건전지}->{컵라면} \nX->Y : if X then Y라는 연관 규칙\nN : 전체 거래 건수\nn(X) : 항목 집합 X의 거래 건수\nn(Y) : 항목 집합 Y의 거래 건수\n\n1) 지지도?\n두 항목 집합 X와 Y의 지지도? 전체 거래 건수 중에서 항목 집합 X와 Y를 모두 포함하는\n거래건수의 비율.\n표기 예) s(X->Y) : X를 구매하면 Y를 구매한다 라는 규칙에 대한 지지도\ns(X->Y) =  X와 Y를 모두 포함하는 거래 건수 / 전체 거래 건수\n\n2)신뢰도?\n항목 집합 X를 포함하는 거래(n(X)) 중에서, 항목 집합 Y를 포함하고 있는 거래의 비율\n(조건부 확률).\n표기 예) c(X->Y) : X를 구매하면 Y를 구매한다 라는 규칙에 대한 신뢰도\nc(X->Y) =  X와 Y를 모두 포함하는 거래 건수 / 항목 집합 X가 포함된 거래 건수\n\n3)향상도?\n항목 집합 X가 주어지지 않았을때의 항목집합 Y의 확률 대비 \n항목 집합 X가 주어졌을때의 항목집합 Y의 확률 증가 비율.\n=> 향상도가 1보다 크거나(+관계) 작다면(-관계) 우연적 기회(random chance)보다\n우수함을 의미. (X와 Y가 서로 독립이면 Lift=1)\n\n표기 예) Lift(X->Y) : 연관규칙의 신뢰도 / 지지도 = c(X->Y) / s(Y)\n-------------------------------------------------------------------------------------\n*예시 데이터( 총 5건, 각 아이템이 2개 이상 중복되는 경우에도 아이템 1개로 간주)*\n거래번호   아이템\n1         계란, 우유\n2         계란, 기저귀, 맥주, 사과\n3         우유, 기저귀, 맥주, 콜라\n4         계란, 우유, 맥주, 기저귀 \n5         계란, 우유, 맥주, 콜라\n\nN=5(전체 거래 건수)\nn(