In [2]:
import pandas as pd
import numpy as np 
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
# TF-IDF : 문장에서 이 단어의 중요도를 알고싶다.
# TF - IDF 로 주제어를 찾는다.
docs = ['먹고 싶은 사과','먹고 싶은 바나나','길고 노란 바나나 바나나','저는 과일이 좋아요']
vocab = list(set(w for doc in docs for w in doc.split()))
vocab.sort()

In [4]:
N = len(docs)

def tf(t,d):
    return d.count(t)

def idf(t):
    df =0
    for doc in docs:
        df += i in doc
    return log(N/(df+1))

def tfidf(t,d):
    return tf(t,d)*idf(t)


In [5]:
result =[]
for i in range(N):
    result.append([])
    d = docs[i]
    for j in range(len(vocab)):
        t = vocab[j]
        result[-1].append(tf(t,d))
        
tf_ = pd.DataFrame(result,columns = vocab)
tf_

과일이  길고  노란  먹고  바나나  사과  싶은  저는  좋아요
0    0   0   0   1    0   1   1   0    0
1    0   0   0   1    1   0   1   0    0
2    0   1   1   0    2   0   0   0    0
3    1   0   0   0    0   0   0   1    1

In [6]:
result =[]
for j in range(len(vocab)):
    t = vocab[j]
    result.append(idf(t))
    
idf_ = pd.DataFrame(result,index = vocab,columns = ['IDF'])
idf_

TypeError: 'in <string>' requires string as left operand, not int

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [9]:
# 사이킷런에 있는 df-idf
corpus = [
    'you know I want your love',
    'I like you',
    'what should I do '   
]

In [10]:
#dtm
vec = CountVectorizer()
vec.fit_transform(corpus).toarray()

array([[0, 1, 0, 1, 0, 1, 0, 1, 1],
       [0, 0, 1, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 1, 0, 1, 0, 0]], dtype=int64)

In [14]:
vec.vocabulary_

{'you': 7,
 'know': 1,
 'want': 5,
 'your': 8,
 'love': 3,
 'like': 2,
 'what': 6,
 'should': 4,
 'do': 0}

In [15]:
# sklearn의 tf-idf 클래스를 사용하여 if-idf 행렬을 구함
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer()
tfidf = tv.fit(corpus)
tfidf.transform(corpus).toarray()

array([[0.        , 0.46735098, 0.        , 0.46735098, 0.        ,
        0.46735098, 0.        , 0.35543247, 0.46735098],
       [0.        , 0.        , 0.79596054, 0.        , 0.        ,
        0.        , 0.        , 0.60534851, 0.        ],
       [0.57735027, 0.        , 0.        , 0.        , 0.57735027,
        0.        , 0.57735027, 0.        , 0.        ]])

In [16]:
tfidf.vocabulary_

{'you': 7,
 'know': 1,
 'want': 5,
 'your': 8,
 'love': 3,
 'like': 2,
 'what': 6,
 'should': 4,
 'do': 0}

In [17]:
tv = TfidfVectorizer(min_df=2)
tfidf = tv.fit(corpus)
tfidf.transform(corpus).toarray()

array([[1.],
       [1.],
       [0.]])

In [18]:
tfidf.vocabulary_

{'you': 0}

In [19]:
tv = TfidfVectorizer(analyzer='char')
tfidf = tv.fit(corpus)
tfidf.transform(corpus).toarray()

array([[0.54522682, 0.14041576, 0.        , 0.14041576, 0.        ,
        0.10904536, 0.14041576, 0.10904536, 0.3692597 , 0.43618145,
        0.18462985, 0.        , 0.14041576, 0.21809073, 0.18462985,
        0.28083152, 0.28083152],
       [0.50040087, 0.        , 0.        , 0.32217861, 0.        ,
        0.50040087, 0.32217861, 0.25020043, 0.        , 0.25020043,
        0.        , 0.        , 0.        , 0.25020043, 0.        ,
        0.        , 0.32217861],
       [0.54546812, 0.17559738, 0.4617789 , 0.        , 0.4617789 ,
        0.13636703, 0.        , 0.13636703, 0.        , 0.27273406,
        0.        , 0.23088945, 0.17559738, 0.13636703, 0.        ,
        0.17559738, 0.        ]])

In [20]:
tfidf.vocabulary_

{'y': 16,
 'o': 9,
 'u': 13,
 ' ': 0,
 'k': 6,
 'n': 8,
 'w': 15,
 'i': 5,
 'a': 1,
 't': 12,
 'r': 10,
 'l': 7,
 'v': 14,
 'e': 3,
 'h': 4,
 's': 11,
 'd': 2}

In [21]:
tv = TfidfVectorizer(ngram_range=(1,2))
tfidf = tv.fit(corpus)
tfidf.transform(corpus).toarray()

array([[0.        , 0.34142622, 0.34142622, 0.        , 0.        ,
        0.34142622, 0.        , 0.        , 0.34142622, 0.34142622,
        0.        , 0.        , 0.25966344, 0.34142622, 0.34142622,
        0.34142622],
       [0.        , 0.        , 0.        , 0.62276601, 0.62276601,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.4736296 , 0.        , 0.        ,
        0.        ],
       [0.4472136 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.4472136 , 0.4472136 , 0.        , 0.        ,
        0.4472136 , 0.4472136 , 0.        , 0.        , 0.        ,
        0.        ]])

In [22]:
tfidf.vocabulary_

{'you': 12,
 'know': 1,
 'want': 8,
 'your': 14,
 'love': 5,
 'you know': 13,
 'know want': 2,
 'want your': 9,
 'your love': 15,
 'like': 3,
 'like you': 4,
 'what': 10,
 'should': 6,
 'do': 0,
 'what should': 11,
 'should do': 7}

In [43]:
import numpy as np
doc1 = np.array((2,3,0,1))
doc2 = np.array((1,2,3,1))
doc3 = np.array((2,1,2,2))

In [44]:
docInput = np.array((1,1,0,1))

In [71]:
# 유클리디안 거리 
([np.sqrt(((doc-docInput)**2).sum()) for doc in [doc1,doc2,doc3]])

[2.23606797749979, 3.1622776601683795, 2.449489742783178]

In [49]:
# 자카드 유사도 알고리즘 
# 교집합 : 두 집합에서 공통으로 기지고 있는 원소 집합
# 합집합 : 두 집합이 가지고 있는 원소 집합
# 합집합에서 교집합의 비율을 구하자 => 두 문서의 유사도 

# j(doc1,doc2) = (doc1 교 doc2) / ( doc1 합 doc2 )
# 0 <= j(doc1,doc2) <= 1

doc1 = "apple banana everyone like likey watch card holder"
doc2 = "apple banana coupon passport love you"

In [50]:
tok1 = doc1.split()
tok2 = doc2.split()
print(tok1)
print(tok2)

['apple', 'banana', 'everyone', 'like', 'likey', 'watch', 'card', 'holder']
['apple', 'banana', 'coupon', 'passport', 'love', 'you']


In [59]:
# 합집합
union = set(tok1)|set(tok2)
union = set(tok1).union(tok2)
union

{'apple',
 'banana',
 'card',
 'coupon',
 'everyone',
 'holder',
 'like',
 'likey',
 'love',
 'passport',
 'watch',
 'you'}

In [60]:
intersection = set(tok1)&set(tok2)
intersection = set(tok1).intersection(tok2)
intersection

{'apple', 'banana'}

In [62]:
print(len(intersection)/len(union))
# 어떤 단어를 버리고 어떤 단어를 선택할 것인가...
# 단어의 순서 고려 x , 유사단어 처리 x
# 단순한 문장 2개 정도는 비교 가능보이지만 문단 자체를 사용하기에는 어려워보인다.


0.16666666666666666


In [63]:
#퀴즈2 코사인 유사도
doc1 = np.array((2,3,0,1))
doc2 = np.array((1,2,3,1))
doc3 = np.array((2,1,2,2))
docInput = np.array((1,1,0,1))

In [70]:
# 코사인 유사도 
def cos_sim(d1,d2):
    return d1@d2 / (np.linalg.norm(d1)*np.linalg.norm(d2))

print(cos_sim(docInput,doc1))
print(cos_sim(docInput,doc2))
print(cos_sim(docInput,doc3))


0.9258200997725515
0.5962847939999439
0.8006407690254358


In [ ]:
# 케글 영화 데이터 
# 메타데이터 

In [72]:
# tf-idf(줄거리) & cos sim => 영화 추천 
# 영화제목 입력 -> 새로운 영화 추천 
# 줄거리 기준으로 ==> 코사인 유사도 

In [73]:
import pandas as pd 

In [74]:
data = pd.read_csv('movies_metadata.csv',low_memory=False) # 대용량 text 데이터 읽을때 low_memory = False // 데이터 읽을 때 컬럼의 타입을 예측
# 그것을 예측하는데 오래걸리는데 low_memory = False 하면 시간 절약 

In [75]:
data.shape

(45466, 24)

In [76]:
data.head()

adult                              belongs_to_collection    budget  \
0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000   
1  False                                                NaN  65000000   
2  False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0   
3  False                                                NaN  16000000   
4  False  {'id': 96871, 'name': 'Father of the Bride Col...         0   

                                              genres  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   
2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...   
3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
4                     [{'id': 35, 'name': 'Comedy'}]   

                               homepage     id    imdb_id original_language  \
0  http://toystory.disney.com/toy-story    862  tt0114709                en   
1                                   NaN   8844  tt0113497                en   
2                                   NaN  15602  tt0113228                en   
3                                   NaN  31357  tt0114885                en   
4                                   NaN  11862  tt0113041                en   

                original_title  \
0                    Toy Story   
1                      Jumanji   
2             Grumpier Old Men   
3            Waiting to Exhale   
4  Father of the Bride Part II   

                                            overview  ... release_date  \
0  Led by Woody, Andy's toys live happily in his ...  ...   1995-10-30   
1  When siblings Judy and Peter discover an encha...  ...   1995-12-15   
2  A family wedding reignites the ancient feud be...  ...   1995-12-22   
3  Cheated on, mistreated and stepped on, the wom...  ...   1995-12-22   
4  Just when George Banks has recovered from his ...  ...   1995-02-10   

       revenue runtime                                   spoken_languages  \
0  373554033.0    81.0           [{'iso_639_1': 'en', 'name': 'English'}]   
1  262797249.0   104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...   
2          0.0   101.0           [{'iso_639_1': 'en', 'name': 'English'}]   
3   81452156.0   127.0           [{'iso_639_1': 'en', 'name': 'English'}]   
4   76578911.0   106.0           [{'iso_639_1': 'en', 'name': 'English'}]   

     status                                            tagline  \
0  Released                                                NaN   
1  Released          Roll the dice and unleash the excitement!   
2  Released  Still Yelling. Still Fighting. Still Ready for...   
3  Released  Friends are the people who let you be yourself...   
4  Released  Just When His World Is Back To Normal... He's ...   

                         title  video vote_average vote_count  
0                    Toy Story  False          7.7     5415.0  
1                      Jumanji  False          6.9     2413.0  
2             Grumpier Old Men  False          6.5       92.0  
3            Waiting to Exhale  False          6.1       34.0  
4  Father of the Bride Part II  False          5.7      173.0  

[5 rows x 24 columns]

In [78]:
data = data.head(20000) # 데이터를 줄인다.

In [80]:
data.shape

(20000, 24)

In [82]:
data.overview
# 전처리 해줘야한다.


0        Led by Woody, Andy's toys live happily in his ...
1        When siblings Judy and Peter discover an encha...
2        A family wedding reignites the ancient feud be...
3        Cheated on, mistreated and stepped on, the wom...
4        Just when George Banks has recovered from his ...
                               ...                        
19995    Dissidents in a French colony attack a police ...
19996    A young mother Nina and her son Enzo find them...
19997    An in-depth analysis of the relationship betwe...
19998    Follows the life and work of animator Lotte Re...
19999    An in-depth look at the genesis, production, a...
Name: overview, Length: 20000, dtype: object

In [83]:
data.overview.isnull().sum()
## null 값은 '' 으로 대체

135

In [84]:
data['overview'] = data['overview'].fillna('')

In [85]:
data['overview'].isnull().sum()

0

In [128]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfMat = TfidfVectorizer(stop_words='english')
tfidfMat= tfidfMat.fit_transform(data['overview'])
tfidfMat.shape

(20000, 47487)

In [129]:
#(20000, 47487) 2만개 데이터 47천여개 단어 
tfidfMat[0].toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [122]:
# 문제 
print(np.max(tfidf[0].toarray()[0]))

0.5036643709879097


In [132]:
tfidfMat = TfidfVectorizer(stop_words='english')
tfidf= tfidfMat.fit_transform(data['overview'])
print(pd.Series(tfidf[0].toarray()[0],index = sorted(tfidfMat.vocabulary_)).idxmax())
tfidfMat= tfidfMat.fit_transform(data['overview'])

buzz


In [127]:
tfidf[0].toarray().argmax() #최대 tfidx 값에 해당되는 단어 index

6290

In [131]:
from sklearn.metrics.pairwise import linear_kernel

In [133]:
cos_sim = linear_kernel(tfidfMat,tfidfMat)

In [134]:
cos_sim.shape

(20000, 20000)

In [136]:
cos_sim[0] # 모든 영화와 코사인 유사도 

array([1.        , 0.01575748, 0.        , ..., 0.        , 0.        ,
       0.        ])

In [137]:
data['title']

0                                                Toy Story
1                                                  Jumanji
2                                         Grumpier Old Men
3                                        Waiting to Exhale
4                              Father of the Bride Part II
                               ...                        
19995                                            Rebellion
19996                                           Versailles
19997                                      Two in the Wave
19998    Lotte Reiniger: Homage to the Inventor of the ...
19999    RKO Production 601: The Making of 'Kong, the E...
Name: title, Length: 20000, dtype: object

In [140]:
indices = pd.Series(data.index,index = data['title'])
indices

title
Toy Story                                                                       0
Jumanji                                                                         1
Grumpier Old Men                                                                2
Waiting to Exhale                                                               3
Father of the Bride Part II                                                     4
                                                                            ...  
Rebellion                                                                   19995
Versailles                                                                  19996
Two in the Wave                                                             19997
Lotte Reiniger: Homage to the Inventor of the Silhouette Film               19998
RKO Production 601: The Making of 'Kong, the Eighth Wonder of the World'    19999
Length: 20000, dtype: int64

In [141]:
indices['Jumanji']
# 영화와 코사인 유사도가 높은 20편

1

In [151]:
ind = pd.DataFrame(cos_sim,index = indices , columns = indices.index)['Jumanji'].sort_values()[::-1][1:21]
data['title'].loc[ind.index]

6166                       Brainscan
8801                         Quintet
17223                 The Dark Angel
9503                       Word Wars
13601    The Mindscape of Alan Moore
16843                         DeVour
8079                         Masques
6055                Poolhall Junkies
19726                 Wreck-It Ralph
2486                        eXistenZ
10892                     Stay Alive
13711                     Rhinoceros
1506              The Innocent Sleep
9107                         Nirvana
19345                       The Wave
10703                  Grandma's Boy
7749              The Last of Sheila
14166                          Gamer
12726           Battlefield Baseball
15512                Le Pont du Nord
Name: title, dtype: object